import { NextResponse } from "next/server";

/**
 * Serves admin-uploaded images from Netlify Blobs, where the filesystem is
 * read-only. Self-hosted deployments write into public/uploads/media/ and are
 * served straight off disk, so they never reach this route.
 */
export async function GET(_req: Request, { params }: { params: Promise<{ key: string }> }) {
  const { key } = await params;

  // keys are generated by lib/media.ts: slug-hash.ext, no separators
  if (!/^[a-z0-9-]+\.(jpg|png|webp|avif)$/.test(key)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const { getStore } = await import("@netlify/blobs");
  const store = getStore("media");
  const blob = await store.getWithMetadata(key, { type: "arrayBuffer" });
  if (!blob) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const contentType = (blob.metadata?.contentType as string) ?? "image/jpeg";
  return new Response(blob.data, {
    headers: {
      "Content-Type": contentType,
      // a key is unique per upload, so the bytes behind it never change
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
